

-- enable or disable specific perks here

ENABLE_ACID_IMMUNE_PERK = false -- does not work

ENABLE_LAVA_IMMUNE_PERK = false -- does not work

ENABLE_ARSENAL_PERK = false -- does not work

ENABLE_WAND_BUFF_PERK = true

ENABLE_BLEED_PHEROMONES_PERK = true

ENABLE_BLEED_BERSERKIUM_PERK = true

ENABLE_STOMPY_PERK = true

ENABLE_IRONSKIN_PERK = true

ENABLE_BARKSKIN_PERK = true

ENABLE_ACID_AURA_PERK = true

ENABLE_LAVA_AURA_PERK = true

ENABLE_TOXIN_AURA_PERK = true

ENABLE_REPEL_FIELD_PERK = true

ENABLE_ICE_TRAIL_PERK = true

ENABLE_FIRE_TRAIL_PERK = true

ENABLE_INFERNO_PERK = true

ENABLE_BLOODPACT_PERK = true

ENABLE_PERKS_4_SALE_PERK = true

ENABLE_PIXIE_PERK = true

ENABLE_GORGON_PERK = true

ENABLE_POLTERGEIST_PERK = true

ENABLE_ADAPTIVE_RESIST_PERK = true
